services:
    service-pg:
        image: bitnami/postgresql
        ports:
            - "5430:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=devmaster
            - POSTGRES_DB=tolinedb

    service-redis:
        image: bitnami/redis
        ports:
            - "6370:6379"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
